# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Set environment variables for the PostgreSQL instance
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB blog_system

# Copy initialization scripts into the image
COPY ./create.sql /docker-entrypoint-initdb.d/
COPY ./insert.sql /docker-entrypoint-initdb.d/

# The scripts in /docker-entrypoint-initdb.d/ will be executed during container startup

# Expose the PostgreSQL port (default is 5432)
EXPOSE 5432
